name: Cache

on:
  workflow_call:
    outputs:
      npm-cache-key:
        value: ${{ jobs.keys.outputs.npm }}
      npm-cache-path:
        value: ${{ jobs.yarn.outputs.cache-path }}

jobs:
  keys:
    name: Cache Keys
    runs-on: ubuntu-latest
    outputs:
      npm: ${{ steps.npm-cache-key.outputs.value }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: NPM Version
        id: npm
        run: echo "version=$(npm --version)" >> $GITHUB_OUTPUT

      - name: Yarn Cache Key
        id: npm-cache-key
        run: echo "value=${{ runner.os }}-node-${{ steps.node.outputs.node-version }}-npm-${{ steps.npm.outputs.version }}-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT

  yarn:
    name: Prime NPM Cache
    needs: [keys]
    runs-on: ubuntu-latest
    env:
      CACHE_PATH: |
        ~/.cache
        .yarn/unplugged
        .yarn/install-state.gz
    concurrency:
      group: ${{ needs.keys.outputs.npm }}
    outputs:
      cache-path: ${{ env.CACHE_PATH }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ needs.keys.outputs.npm }}

      - name: NPM
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
