name: Create Ref

on: create

jobs:
  check-cache:
    name: Check Yarn Cache
    runs-on: ubuntu-latest
    if: contains(github.ref, "/dependabot/npm_and_yarn/")
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check dependencies
        run: yarn --check-cache
      - uses: EndBug/add-and-commit@v7
        with:
          add: .yarn .pnp.js yarn.lock
          message: 'chore(package): update dependencies'
