name: Dependabot

on:
  pull_request_target:
    types: [opened]

jobs:
  check-cache:
    name: Check Yarn Cache
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check dependencies
        run: yarn --check-cache
      - uses: EndBug/add-and-commit@v7
        with:
          add: .yarn .pnp.js yarn.lock
          message: 'chore(package): update dependencies'

  auto-merge:
    name: Auto Merge
    needs: [check-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Check project
        uses: actions/checkout@v2
      - name: Auto appove
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.PUSH_TOKEN }}
