name: Pull Request

on:
  pull_request:

jobs:
  cache:
    uses: ./.github/workflows/cache.yml

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [cache]

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ needs.cache.outputs.npm-cache-key }}
          path: ${{ needs.cache.outputs.npm-cache-path }}

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
